config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :line_items
  resources :carts
  resources :products do
    resources :reviews
  end
  devise_for :users, controllers: { registrations: 'users/registrations',omniauth_callbacks: 'users/omniauth_callbacks'  }
  root 'products#index'

  post "checkout/create", to: "checkout#create"
  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_one_attached :image
  has_many :line_items
  belongs_to :category
  has_many :reviews

  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :name, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
  validates :price, length: { maximum: 7 }


  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products or /products.json
  def index
    if params[:category].blank?
      @products = Product.all.order("created_at desc")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
    @categories = Category.all.map{|c| [c.name, c.id]}
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{|c| [c.name, c.id]}
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.build(product_params)
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      @product.category_id = params[:category_id]
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.input :name%>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.file_field :image %><br>
  <%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/products/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-product-form">
    <h1>Edit Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', products_path %>

  </div>
</div>

app/views/products/index.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Browse the latest Products on ShopingStore
        </h1>
      </div>
    </div>
  </section>
<% end %>

<h1 class="current-category"><%= params[:category] %></h1>

<% if @products.count == 0 %>

  <h1>There are no books currently in this category</h1>

<% else %>

<div class="product-index-grid pt4">
  <% @products.each do |product| %>

    <div class="product border-light">
      <div class="product-thumb">
        <%= image_tag(product.image, size: '200x250',class: "product-show") if product.image.attached?%>

      </div>


      <div class="pa3">

        <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>
        <h6 class="has-text-gray fg pt1">Sold by <%= product.user.name %></h6><br>
        <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(product.price) %></p>

        <%= link_to 'show', product , class: "button is-small" %>


      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/products/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-product-form">
    <h1>New Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section product-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @product.name %></h1>

      <div class="feature-image">
        <%= image_tag(@product.image, size: '200x250', class: "product-show") if @product.image.attached? %>
      </div>
      <div style="margin-left: 30px; margin-top: 10px">
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_product_path(@product) %> |
          <%= link_to 'Delete', @product, method: :delete, data: { confirm: "Are you sure ?" } %> |
        <% end %>
        <%= link_to 'Back', products_path %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">
        <h3 class="subtitle is-4">Category</h3>
        <%= @product.category.name %>
        <h3 class="subtitle is-4">Description</h3>
        <%= @product.description %>
        <br>

      </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@product.price) %></h4>
        <%= button_to 'Add to cart', line_items_path(product_id: @product), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>
  <div class="column is-8">
    <div class="content pa4 mt3 bg-white border-radius-3">
      <div class="reviews">
        <!-- Where the reviews/ratings will go -->
        <h1>Reviews</h1>
        <%= render @product.reviews %>
        <div>
          <%= link_to "Add Review", new_product_review_path(@product), class: "btn-custom" %>
        </div>
      </div>
    </div>
  </div>
</section>