config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :line_items
  resources :carts
  resources :products do
    resources :reviews
  end
  devise_for :users, controllers: { registrations: 'users/registrations',omniauth_callbacks: 'users/omniauth_callbacks'  }
  root 'products#index'

  post "checkout/create", to: "checkout#create"
  get "success", to: "checkout#success"
  get "cancel", to: "checkout#cancel"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5">ShopingStore</h1>
    <% end  %>
    <div id="navbar" class="navbar-menu">
    <%= link_to 'Products', products_path, class: "navbar-item button is-dark" %>
    </div>
    <div class="navbar-burger burger" data-target="navbar">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">

          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="navbar-item button is-dark" data-toggle="dropdown" role="button" >Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, products_path(category: category.name), class: "link" %>
                </li>
              <% end %>
            </ul>
          </li>
          <% end %>

          <% if total_cart_items %>
            <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%= cart_count_over_one %>
                </span>
            <% end %>
          <% end %>

          <% if user_signed_in? %>

            <%= link_to 'Sell', new_product_path, class: "navbar-item button is-dark" %>
            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to current_user.name, edit_user_registration_path, class: "navbar-link" %>
              <div class="navbar-dropdown is-right">
                <%= link_to 'Account', edit_user_registration_path, class:"navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </div>
            </div>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopingStore</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= yield (:body_class) %>">
<%= render 'layouts/navbar' %>

<%= yield(:header) %>

<div class="container">

  <%= yield %>

</div>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>


</body>
</html>